# .travis.yml

dist: xenial

language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

install:
    - echo Nice

script:
    - python3 udpflood.py < .test

after_script:
    - bash <(curl -s https://codecov.io/bash)
